macro(DetermineCompilerTarget OUTPUT_VAR)
 if("${CMAKE_C_COMPILER_ID}" MATCHES "clang" OR "${CMAKE_C_COMPILER_ID}" MATCHES "Clang")
  set(CLANG 1)
 endif("${CMAKE_C_COMPILER_ID}" MATCHES "clang" OR "${CMAKE_C_COMPILER_ID}" MATCHES "Clang")
 if(CMAKE_COMPILER_IS_GNUCC OR MINGW OR CLANG)
  execute_process(COMMAND ${CMAKE_C_COMPILER} -dumpmachine OUTPUT_VARIABLE ${OUTPUT_VAR})
 elseif(MSVC)
  math(EXPR MSVC_TARGET_BITNESS "${CMAKE_SIZEOF_VOID_P}*8")
  set(${OUTPUT_VAR} "msvc-win${MSVC_TARGET_BITNESS}")
 endif()
 string(STRIP "${${OUTPUT_VAR}}" ${OUTPUT_VAR})
endmacro()